/**
 * Differential gate: TS DKIM signing/verification vs the C# crypto oracle
 * (oracle-dkim, which references the FULL MimeKit with its own DkimSigner/
 * DkimVerifier). Generated by `node gates/oracle-gen.mjs dkim`.
 *
 * (1) Byte-parity: with the t= timestamp pinned, DKIM signing is fully
 *     deterministic, so the TS DkimSigner must reproduce MimeKit's
 *     DKIM-Signature header value BYTE-FOR-BYTE for every fixture × canon × algo.
 * (2) Cross-verify (oracle -> TS): the TS DkimVerifier must verify every
 *     message MimeKit signed. Combined with byte-parity (which proves the TS
 *     signature is byte-identical to MimeKit's, hence verifiable by MimeKit),
 *     this establishes bidirectional wire-format + semantic parity.
 *
 * ANTI-FACADE: the TS crypto never imports/reads the oracle; primitives come
 * only from WebCrypto + @noble. The oracle is a separate C# process whose
 * outputs are checked in here as opaque fixtures.
 */
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, test } from 'vitest';
import '../../src/index.js';
import { MimeMessage } from '../../src/mime-message.js';
import { HeaderId } from '../../src/header-id.js';
import { DkimSigner } from '../../src/dkim/dkim-signer.js';
import { DkimVerifier } from '../../src/dkim/dkim-verifier.js';
import { DkimSignatureAlgorithm } from '../../src/dkim/dkim-signature-algorithm.js';
import { DkimCanonicalizationAlgorithm } from '../../src/dkim/dkim-canonicalization-algorithm.js';
import { parseDkimPublicKey, type AsymmetricKey } from '../../src/dkim/crypto.js';
import type { DkimPublicKeyLocator } from '../../src/dkim/dkim-public-key-locator.js';
import { testDataDir } from './helpers.js';

const dkimOutDir = join(__dirname, '..', '..', 'gates', 'out', 'oracle', 'dkim');

function loadJson(rel: string): { domain: string; selector: string; t: number; sign: Record<string, string> } {
  return JSON.parse(readFileSync(join(dkimOutDir, rel), 'utf8'));
}

function loadMessage(bytes: Uint8Array): MimeMessage {
  const r = MimeMessage.load(bytes);
  if (!r.ok) throw new Error(`${r.error.kind}: ${r.error.message}`);
  return r.value;
}

const ALGO: Record<string, DkimSignatureAlgorithm> = {
  'rsa-sha1': DkimSignatureAlgorithm.RsaSha1,
  'rsa-sha256': DkimSignatureAlgorithm.RsaSha256,
  'ed25519-sha256': DkimSignatureAlgorithm.Ed25519Sha256,
};
const CANON: Record<string, DkimCanonicalizationAlgorithm> = {
  relaxed: DkimCanonicalizationAlgorithm.Relaxed,
  simple: DkimCanonicalizationAlgorithm.Simple,
};

/** A DkimSigner with a pinned timestamp, matching the oracle's fixture. */
class FixedDkimSigner extends DkimSigner {
  constructor(private readonly fixedT: number, key: string, domain: string, selector: string, algorithm: DkimSignatureAlgorithm) {
    super(key, domain, selector, algorithm);
  }
  protected override getTimestamp(): number {
    return this.fixedT;
  }
}

function examplePub(): AsymmetricKey {
  const pem = readFileSync(join(testDataDir, 'dkim', 'example.pub'), 'utf8');
  return parseDkimPublicKey('rsa', pem.replace(/-----[^-]+-----/g, '').replace(/\s+/g, ''));
}

function dummyLocator(key: AsymmetricKey): DkimPublicKeyLocator {
  return { locatePublicKey: () => Promise.resolve(key) };
}

const meta = loadJson('sign.json');
const examplePem = readFileSync(join(testDataDir, 'dkim', 'example.pem'), 'utf8');

describe('dkim gate: byte-parity (TS sign == oracle sign)', () => {
  test.each(Object.keys(meta.sign))('%s', async (key) => {
    const [fixture, hc, bc, algo] = key.split('|');
    const bytes = new Uint8Array(readFileSync(join(testDataDir, 'dkim', fixture!)));
    const message = loadMessage(bytes);
    const signer = new FixedDkimSigner(meta.t, examplePem, meta.domain, meta.selector, ALGO[algo!]!);
    signer.headerCanonicalizationAlgorithm = CANON[hc!]!;
    signer.bodyCanonicalizationAlgorithm = CANON[bc!]!;
    signer.agentOrUserIdentifier = '@eng.example.com';
    signer.queryMethod = 'dns/txt';

    await signer.sign(message, [HeaderId.From, HeaderId.Subject, HeaderId.Date]);

    expect(message.headers.getValue(HeaderId.DkimSignature)).toBe(meta.sign[key]);
  });
});

describe('dkim gate: cross-verify (oracle-signed -> TS verifies)', () => {
  const signedDir = join(dkimOutDir, 'oracle-signed');
  const files = readdirSync(signedDir).filter((f) => f.endsWith('.eml')).sort();
  const verifier = new DkimVerifier(dummyLocator(examplePub()));
  verifier.enable(DkimSignatureAlgorithm.RsaSha1);

  test.each(files)('%s', async (file) => {
    const message = loadMessage(new Uint8Array(readFileSync(join(signedDir, file))));
    const index = message.headers.indexOf(HeaderId.DkimSignature);
    expect(index).toBeGreaterThanOrEqual(0);
    expect(await verifier.verify(message, message.headers.at(index))).toBe(true);
  });
});
