// Port of MimeKit/Text/HtmlTagId.cs (enum + HtmlTagIdExtensions).

export enum HtmlTagId {
  Unknown = 'Unknown',
  A = 'A',
  Abbr = 'Abbr',
  Acronym = 'Acronym',
  Address = 'Address',
  Applet = 'Applet',
  Area = 'Area',
  Article = 'Article',
  Aside = 'Aside',
  Audio = 'Audio',
  B = 'B',
  Base = 'Base',
  BaseFont = 'BaseFont',
  Bdi = 'Bdi',
  Bdo = 'Bdo',
  BGSound = 'BGSound',
  Big = 'Big',
  Blink = 'Blink',
  BlockQuote = 'BlockQuote',
  Body = 'Body',
  Br = 'Br',
  Button = 'Button',
  Canvas = 'Canvas',
  Caption = 'Caption',
  Center = 'Center',
  Cite = 'Cite',
  Code = 'Code',
  Col = 'Col',
  ColGroup = 'ColGroup',
  Command = 'Command',
  Comment = 'Comment',
  DataList = 'DataList',
  DD = 'DD',
  Del = 'Del',
  Details = 'Details',
  Dfn = 'Dfn',
  Dialog = 'Dialog',
  Dir = 'Dir',
  Div = 'Div',
  DL = 'DL',
  DT = 'DT',
  EM = 'EM',
  Embed = 'Embed',
  FieldSet = 'FieldSet',
  FigCaption = 'FigCaption',
  Figure = 'Figure',
  Font = 'Font',
  Footer = 'Footer',
  Form = 'Form',
  Frame = 'Frame',
  FrameSet = 'FrameSet',
  H1 = 'H1',
  H2 = 'H2',
  H3 = 'H3',
  H4 = 'H4',
  H5 = 'H5',
  H6 = 'H6',
  Head = 'Head',
  Header = 'Header',
  HR = 'HR',
  Html = 'Html',
  I = 'I',
  IFrame = 'IFrame',
  Image = 'Image',
  Input = 'Input',
  Ins = 'Ins',
  IsIndex = 'IsIndex',
  Kbd = 'Kbd',
  Keygen = 'Keygen',
  Label = 'Label',
  Legend = 'Legend',
  LI = 'LI',
  Link = 'Link',
  Listing = 'Listing',
  Main = 'Main',
  Map = 'Map',
  Mark = 'Mark',
  Marquee = 'Marquee',
  Menu = 'Menu',
  MenuItem = 'MenuItem',
  Meta = 'Meta',
  Meter = 'Meter',
  Nav = 'Nav',
  NextId = 'NextId',
  NoBR = 'NoBR',
  NoEmbed = 'NoEmbed',
  NoFrames = 'NoFrames',
  NoScript = 'NoScript',
  Object = 'Object',
  OL = 'OL',
  OptGroup = 'OptGroup',
  Option = 'Option',
  Output = 'Output',
  P = 'P',
  Param = 'Param',
  PlainText = 'PlainText',
  Pre = 'Pre',
  Progress = 'Progress',
  Q = 'Q',
  RP = 'RP',
  RT = 'RT',
  Ruby = 'Ruby',
  S = 'S',
  Samp = 'Samp',
  Script = 'Script',
  Section = 'Section',
  Select = 'Select',
  Small = 'Small',
  Source = 'Source',
  Span = 'Span',
  Strike = 'Strike',
  Strong = 'Strong',
  Style = 'Style',
  Sub = 'Sub',
  Summary = 'Summary',
  Sup = 'Sup',
  Table = 'Table',
  TBody = 'TBody',
  TD = 'TD',
  TextArea = 'TextArea',
  Tfoot = 'Tfoot',
  TH = 'TH',
  THead = 'THead',
  Time = 'Time',
  Title = 'Title',
  TR = 'TR',
  Track = 'Track',
  TT = 'TT',
  U = 'U',
  UL = 'UL',
  Var = 'Var',
  Video = 'Video',
  Wbr = 'Wbr',
  Xml = 'Xml',
  Xmp = 'Xmp',
}

// Enum order (excluding Unknown) paired with the HTML tag name. Note: Comment maps
// to "!" (matching the C# TagNames table).
export const htmlTagIdNameTable = [
  [HtmlTagId.A, 'a'],
  [HtmlTagId.Abbr, 'abbr'],
  [HtmlTagId.Acronym, 'acronym'],
  [HtmlTagId.Address, 'address'],
  [HtmlTagId.Applet, 'applet'],
  [HtmlTagId.Area, 'area'],
  [HtmlTagId.Article, 'article'],
  [HtmlTagId.Aside, 'aside'],
  [HtmlTagId.Audio, 'audio'],
  [HtmlTagId.B, 'b'],
  [HtmlTagId.Base, 'base'],
  [HtmlTagId.BaseFont, 'basefont'],
  [HtmlTagId.Bdi, 'bdi'],
  [HtmlTagId.Bdo, 'bdo'],
  [HtmlTagId.BGSound, 'bgsound'],
  [HtmlTagId.Big, 'big'],
  [HtmlTagId.Blink, 'blink'],
  [HtmlTagId.BlockQuote, 'blockquote'],
  [HtmlTagId.Body, 'body'],
  [HtmlTagId.Br, 'br'],
  [HtmlTagId.Button, 'button'],
  [HtmlTagId.Canvas, 'canvas'],
  [HtmlTagId.Caption, 'caption'],
  [HtmlTagId.Center, 'center'],
  [HtmlTagId.Cite, 'cite'],
  [HtmlTagId.Code, 'code'],
  [HtmlTagId.Col, 'col'],
  [HtmlTagId.ColGroup, 'colgroup'],
  [HtmlTagId.Command, 'command'],
  [HtmlTagId.Comment, '!'],
  [HtmlTagId.DataList, 'datalist'],
  [HtmlTagId.DD, 'dd'],
  [HtmlTagId.Del, 'del'],
  [HtmlTagId.Details, 'details'],
  [HtmlTagId.Dfn, 'dfn'],
  [HtmlTagId.Dialog, 'dialog'],
  [HtmlTagId.Dir, 'dir'],
  [HtmlTagId.Div, 'div'],
  [HtmlTagId.DL, 'dl'],
  [HtmlTagId.DT, 'dt'],
  [HtmlTagId.EM, 'em'],
  [HtmlTagId.Embed, 'embed'],
  [HtmlTagId.FieldSet, 'fieldset'],
  [HtmlTagId.FigCaption, 'figcaption'],
  [HtmlTagId.Figure, 'figure'],
  [HtmlTagId.Font, 'font'],
  [HtmlTagId.Footer, 'footer'],
  [HtmlTagId.Form, 'form'],
  [HtmlTagId.Frame, 'frame'],
  [HtmlTagId.FrameSet, 'frameset'],
  [HtmlTagId.H1, 'h1'],
  [HtmlTagId.H2, 'h2'],
  [HtmlTagId.H3, 'h3'],
  [HtmlTagId.H4, 'h4'],
  [HtmlTagId.H5, 'h5'],
  [HtmlTagId.H6, 'h6'],
  [HtmlTagId.Head, 'head'],
  [HtmlTagId.Header, 'header'],
  [HtmlTagId.HR, 'hr'],
  [HtmlTagId.Html, 'html'],
  [HtmlTagId.I, 'i'],
  [HtmlTagId.IFrame, 'iframe'],
  [HtmlTagId.Image, 'img'],
  [HtmlTagId.Input, 'input'],
  [HtmlTagId.Ins, 'ins'],
  [HtmlTagId.IsIndex, 'isindex'],
  [HtmlTagId.Kbd, 'kbd'],
  [HtmlTagId.Keygen, 'keygen'],
  [HtmlTagId.Label, 'label'],
  [HtmlTagId.Legend, 'legend'],
  [HtmlTagId.LI, 'li'],
  [HtmlTagId.Link, 'link'],
  [HtmlTagId.Listing, 'listing'],
  [HtmlTagId.Main, 'main'],
  [HtmlTagId.Map, 'map'],
  [HtmlTagId.Mark, 'mark'],
  [HtmlTagId.Marquee, 'marquee'],
  [HtmlTagId.Menu, 'menu'],
  [HtmlTagId.MenuItem, 'menuitem'],
  [HtmlTagId.Meta, 'meta'],
  [HtmlTagId.Meter, 'meter'],
  [HtmlTagId.Nav, 'nav'],
  [HtmlTagId.NextId, 'nextid'],
  [HtmlTagId.NoBR, 'nobr'],
  [HtmlTagId.NoEmbed, 'noembed'],
  [HtmlTagId.NoFrames, 'noframes'],
  [HtmlTagId.NoScript, 'noscript'],
  [HtmlTagId.Object, 'object'],
  [HtmlTagId.OL, 'ol'],
  [HtmlTagId.OptGroup, 'optgroup'],
  [HtmlTagId.Option, 'option'],
  [HtmlTagId.Output, 'output'],
  [HtmlTagId.P, 'p'],
  [HtmlTagId.Param, 'param'],
  [HtmlTagId.PlainText, 'plaintext'],
  [HtmlTagId.Pre, 'pre'],
  [HtmlTagId.Progress, 'progress'],
  [HtmlTagId.Q, 'q'],
  [HtmlTagId.RP, 'rp'],
  [HtmlTagId.RT, 'rt'],
  [HtmlTagId.Ruby, 'ruby'],
  [HtmlTagId.S, 's'],
  [HtmlTagId.Samp, 'samp'],
  [HtmlTagId.Script, 'script'],
  [HtmlTagId.Section, 'section'],
  [HtmlTagId.Select, 'select'],
  [HtmlTagId.Small, 'small'],
  [HtmlTagId.Source, 'source'],
  [HtmlTagId.Span, 'span'],
  [HtmlTagId.Strike, 'strike'],
  [HtmlTagId.Strong, 'strong'],
  [HtmlTagId.Style, 'style'],
  [HtmlTagId.Sub, 'sub'],
  [HtmlTagId.Summary, 'summary'],
  [HtmlTagId.Sup, 'sup'],
  [HtmlTagId.Table, 'table'],
  [HtmlTagId.TBody, 'tbody'],
  [HtmlTagId.TD, 'td'],
  [HtmlTagId.TextArea, 'textarea'],
  [HtmlTagId.Tfoot, 'tfoot'],
  [HtmlTagId.TH, 'th'],
  [HtmlTagId.THead, 'thead'],
  [HtmlTagId.Time, 'time'],
  [HtmlTagId.Title, 'title'],
  [HtmlTagId.TR, 'tr'],
  [HtmlTagId.Track, 'track'],
  [HtmlTagId.TT, 'tt'],
  [HtmlTagId.U, 'u'],
  [HtmlTagId.UL, 'ul'],
  [HtmlTagId.Var, 'var'],
  [HtmlTagId.Video, 'video'],
  [HtmlTagId.Wbr, 'wbr'],
  [HtmlTagId.Xml, 'xml'],
  [HtmlTagId.Xmp, 'xmp'],
] as const;

const idToName = new Map<HtmlTagId, string>(htmlTagIdNameTable);
const nameToId = new Map<string, HtmlTagId>(
  htmlTagIdNameTable.map(([id, name]) => [name.toLowerCase(), id]),
);

const tagIdValues = new Set<string>(Object.values(HtmlTagId));

/**
 * Whether `value` is one of the HtmlTagId enum values. Used to disambiguate the
 * C# id/name overloads that collapse to a single TS signature.
 */
export function isHtmlTagId(value: unknown): value is HtmlTagId {
  return typeof value === 'string' && tagIdValues.has(value);
}

/** Converts the enum value into the equivalent tag name. */
export function toHtmlTagName(value: HtmlTagId): string {
  return idToName.get(value) ?? String(value);
}

/** Converts the tag name into the equivalent tag id. */
export function toHtmlTagId(name: string | null | undefined): HtmlTagId {
  if (name === null || name === undefined || name.length === 0) return HtmlTagId.Unknown;

  if (name[0] === '!') return HtmlTagId.Comment;

  return nameToId.get(name.toLowerCase()) ?? HtmlTagId.Unknown;
}

const emptyElements = new Set<HtmlTagId>([
  HtmlTagId.Area,
  HtmlTagId.Base,
  HtmlTagId.Br,
  HtmlTagId.Col,
  HtmlTagId.Command,
  HtmlTagId.Embed,
  HtmlTagId.HR,
  HtmlTagId.Image,
  HtmlTagId.Input,
  HtmlTagId.Keygen,
  HtmlTagId.Link,
  HtmlTagId.Meta,
  HtmlTagId.Param,
  HtmlTagId.Source,
  HtmlTagId.Track,
  HtmlTagId.Wbr,
]);

/** Determines whether the HTML tag is an empty element. */
export function isEmptyElement(id: HtmlTagId): boolean {
  return emptyElements.has(id);
}

const formattingElements = new Set<HtmlTagId>([
  HtmlTagId.A,
  HtmlTagId.B,
  HtmlTagId.Big,
  HtmlTagId.Code,
  HtmlTagId.EM,
  HtmlTagId.Font,
  HtmlTagId.I,
  HtmlTagId.NoBR,
  HtmlTagId.S,
  HtmlTagId.Small,
  HtmlTagId.Strike,
  HtmlTagId.Strong,
  HtmlTagId.TT,
  HtmlTagId.U,
]);

/** Determines whether the HTML tag is a formatting element. */
export function isFormattingElement(id: HtmlTagId): boolean {
  return formattingElements.has(id);
}
