// Port of MimeKit/Text/HtmlAttributeId.cs (enum + HtmlAttributeIdExtensions).

export enum HtmlAttributeId {
  Unknown = 'Unknown',
  Abbr = 'Abbr',
  Accept = 'Accept',
  AcceptCharset = 'AcceptCharset',
  AccessKey = 'AccessKey',
  Action = 'Action',
  Align = 'Align',
  Alink = 'Alink',
  Alt = 'Alt',
  Archive = 'Archive',
  Axis = 'Axis',
  Background = 'Background',
  BGColor = 'BGColor',
  Border = 'Border',
  CellPadding = 'CellPadding',
  CellSpacing = 'CellSpacing',
  Char = 'Char',
  CharOff = 'CharOff',
  Charset = 'Charset',
  Checked = 'Checked',
  Cite = 'Cite',
  Class = 'Class',
  ClassId = 'ClassId',
  Clear = 'Clear',
  Code = 'Code',
  CodeBase = 'CodeBase',
  CodeType = 'CodeType',
  Color = 'Color',
  Cols = 'Cols',
  ColSpan = 'ColSpan',
  Compact = 'Compact',
  Content = 'Content',
  Coords = 'Coords',
  Data = 'Data',
  DateTime = 'DateTime',
  Declare = 'Declare',
  Defer = 'Defer',
  Dir = 'Dir',
  Disabled = 'Disabled',
  DynSrc = 'DynSrc',
  EncType = 'EncType',
  Face = 'Face',
  For = 'For',
  Frame = 'Frame',
  FrameBorder = 'FrameBorder',
  Headers = 'Headers',
  Height = 'Height',
  Href = 'Href',
  HrefLang = 'HrefLang',
  Hspace = 'Hspace',
  HttpEquiv = 'HttpEquiv',
  Id = 'Id',
  IsMap = 'IsMap',
  Label = 'Label',
  Lang = 'Lang',
  Language = 'Language',
  LeftMargin = 'LeftMargin',
  Link = 'Link',
  LongDesc = 'LongDesc',
  LowSrc = 'LowSrc',
  MarginHeight = 'MarginHeight',
  MarginWidth = 'MarginWidth',
  MaxLength = 'MaxLength',
  Media = 'Media',
  Method = 'Method',
  Multiple = 'Multiple',
  Name = 'Name',
  NoHref = 'NoHref',
  NoResize = 'NoResize',
  NoShade = 'NoShade',
  NoWrap = 'NoWrap',
  Object = 'Object',
  Profile = 'Profile',
  Prompt = 'Prompt',
  ReadOnly = 'ReadOnly',
  Rel = 'Rel',
  Rev = 'Rev',
  Rows = 'Rows',
  RowSpan = 'RowSpan',
  Rules = 'Rules',
  Scheme = 'Scheme',
  Scope = 'Scope',
  Scrolling = 'Scrolling',
  Selected = 'Selected',
  Shape = 'Shape',
  Size = 'Size',
  Span = 'Span',
  Src = 'Src',
  StandBy = 'StandBy',
  Start = 'Start',
  Style = 'Style',
  Summary = 'Summary',
  TabIndex = 'TabIndex',
  Target = 'Target',
  Text = 'Text',
  Title = 'Title',
  TopMargin = 'TopMargin',
  Type = 'Type',
  UseMap = 'UseMap',
  Valign = 'Valign',
  Value = 'Value',
  ValueType = 'ValueType',
  Version = 'Version',
  Vlink = 'Vlink',
  Vspace = 'Vspace',
  Width = 'Width',
  XmlNS = 'XmlNS',
}

// Enum order (excluding Unknown) paired with the HTML attribute name.
export const htmlAttributeIdNameTable = [
  [HtmlAttributeId.Abbr, 'abbr'],
  [HtmlAttributeId.Accept, 'accept'],
  [HtmlAttributeId.AcceptCharset, 'accept-charset'],
  [HtmlAttributeId.AccessKey, 'accesskey'],
  [HtmlAttributeId.Action, 'action'],
  [HtmlAttributeId.Align, 'align'],
  [HtmlAttributeId.Alink, 'alink'],
  [HtmlAttributeId.Alt, 'alt'],
  [HtmlAttributeId.Archive, 'archive'],
  [HtmlAttributeId.Axis, 'axis'],
  [HtmlAttributeId.Background, 'background'],
  [HtmlAttributeId.BGColor, 'bgcolor'],
  [HtmlAttributeId.Border, 'border'],
  [HtmlAttributeId.CellPadding, 'cellpadding'],
  [HtmlAttributeId.CellSpacing, 'cellspacing'],
  [HtmlAttributeId.Char, 'char'],
  [HtmlAttributeId.CharOff, 'charoff'],
  [HtmlAttributeId.Charset, 'charset'],
  [HtmlAttributeId.Checked, 'checked'],
  [HtmlAttributeId.Cite, 'cite'],
  [HtmlAttributeId.Class, 'class'],
  [HtmlAttributeId.ClassId, 'classid'],
  [HtmlAttributeId.Clear, 'clear'],
  [HtmlAttributeId.Code, 'code'],
  [HtmlAttributeId.CodeBase, 'codebase'],
  [HtmlAttributeId.CodeType, 'codetype'],
  [HtmlAttributeId.Color, 'color'],
  [HtmlAttributeId.Cols, 'cols'],
  [HtmlAttributeId.ColSpan, 'colspan'],
  [HtmlAttributeId.Compact, 'compact'],
  [HtmlAttributeId.Content, 'content'],
  [HtmlAttributeId.Coords, 'coords'],
  [HtmlAttributeId.Data, 'data'],
  [HtmlAttributeId.DateTime, 'datetime'],
  [HtmlAttributeId.Declare, 'declare'],
  [HtmlAttributeId.Defer, 'defer'],
  [HtmlAttributeId.Dir, 'dir'],
  [HtmlAttributeId.Disabled, 'disabled'],
  [HtmlAttributeId.DynSrc, 'dynsrc'],
  [HtmlAttributeId.EncType, 'enctype'],
  [HtmlAttributeId.Face, 'face'],
  [HtmlAttributeId.For, 'for'],
  [HtmlAttributeId.Frame, 'frame'],
  [HtmlAttributeId.FrameBorder, 'frameborder'],
  [HtmlAttributeId.Headers, 'headers'],
  [HtmlAttributeId.Height, 'height'],
  [HtmlAttributeId.Href, 'href'],
  [HtmlAttributeId.HrefLang, 'hreflang'],
  [HtmlAttributeId.Hspace, 'hspace'],
  [HtmlAttributeId.HttpEquiv, 'http-equiv'],
  [HtmlAttributeId.Id, 'id'],
  [HtmlAttributeId.IsMap, 'ismap'],
  [HtmlAttributeId.Label, 'label'],
  [HtmlAttributeId.Lang, 'lang'],
  [HtmlAttributeId.Language, 'language'],
  [HtmlAttributeId.LeftMargin, 'leftmargin'],
  [HtmlAttributeId.Link, 'link'],
  [HtmlAttributeId.LongDesc, 'longdesc'],
  [HtmlAttributeId.LowSrc, 'lowsrc'],
  [HtmlAttributeId.MarginHeight, 'marginheight'],
  [HtmlAttributeId.MarginWidth, 'marginwidth'],
  [HtmlAttributeId.MaxLength, 'maxlength'],
  [HtmlAttributeId.Media, 'media'],
  [HtmlAttributeId.Method, 'method'],
  [HtmlAttributeId.Multiple, 'multiple'],
  [HtmlAttributeId.Name, 'name'],
  [HtmlAttributeId.NoHref, 'nohref'],
  [HtmlAttributeId.NoResize, 'noresize'],
  [HtmlAttributeId.NoShade, 'noshade'],
  [HtmlAttributeId.NoWrap, 'nowrap'],
  [HtmlAttributeId.Object, 'object'],
  [HtmlAttributeId.Profile, 'profile'],
  [HtmlAttributeId.Prompt, 'prompt'],
  [HtmlAttributeId.ReadOnly, 'readonly'],
  [HtmlAttributeId.Rel, 'rel'],
  [HtmlAttributeId.Rev, 'rev'],
  [HtmlAttributeId.Rows, 'rows'],
  [HtmlAttributeId.RowSpan, 'rowspan'],
  [HtmlAttributeId.Rules, 'rules'],
  [HtmlAttributeId.Scheme, 'scheme'],
  [HtmlAttributeId.Scope, 'scope'],
  [HtmlAttributeId.Scrolling, 'scrolling'],
  [HtmlAttributeId.Selected, 'selected'],
  [HtmlAttributeId.Shape, 'shape'],
  [HtmlAttributeId.Size, 'size'],
  [HtmlAttributeId.Span, 'span'],
  [HtmlAttributeId.Src, 'src'],
  [HtmlAttributeId.StandBy, 'standby'],
  [HtmlAttributeId.Start, 'start'],
  [HtmlAttributeId.Style, 'style'],
  [HtmlAttributeId.Summary, 'summary'],
  [HtmlAttributeId.TabIndex, 'tabindex'],
  [HtmlAttributeId.Target, 'target'],
  [HtmlAttributeId.Text, 'text'],
  [HtmlAttributeId.Title, 'title'],
  [HtmlAttributeId.TopMargin, 'topmargin'],
  [HtmlAttributeId.Type, 'type'],
  [HtmlAttributeId.UseMap, 'usemap'],
  [HtmlAttributeId.Valign, 'valign'],
  [HtmlAttributeId.Value, 'value'],
  [HtmlAttributeId.ValueType, 'valuetype'],
  [HtmlAttributeId.Version, 'version'],
  [HtmlAttributeId.Vlink, 'vlink'],
  [HtmlAttributeId.Vspace, 'vspace'],
  [HtmlAttributeId.Width, 'width'],
  [HtmlAttributeId.XmlNS, 'xmlns'],
] as const;

const idToName = new Map<HtmlAttributeId, string>(htmlAttributeIdNameTable);
const nameToId = new Map<string, HtmlAttributeId>(
  htmlAttributeIdNameTable.map(([id, name]) => [name.toLowerCase(), id]),
);

const attributeIdValues = new Set<string>(Object.values(HtmlAttributeId));

/**
 * Whether `value` is one of the HtmlAttributeId enum values. Used to
 * disambiguate the C# id/name overloads that collapse to a single TS signature.
 */
export function isHtmlAttributeId(value: unknown): value is HtmlAttributeId {
  return typeof value === 'string' && attributeIdValues.has(value);
}

/** Converts the enum value into the equivalent attribute name. */
export function toAttributeName(value: HtmlAttributeId): string {
  return idToName.get(value) ?? String(value);
}

/** Converts the attribute name into the equivalent attribute id. */
export function toHtmlAttributeId(name: string | null | undefined): HtmlAttributeId {
  if (name === null || name === undefined) return HtmlAttributeId.Unknown;
  return nameToId.get(name.toLowerCase()) ?? HtmlAttributeId.Unknown;
}
