// Port of MimeKit/HeaderId.cs.

/**
 * Identifies well-known message header fields.
 */
export enum HeaderId {
  AcceptLanguage = "AcceptLanguage",
  AdHoc = "AdHoc",
  AlternateRecipient = "AlternateRecipient",
  ApparentlyTo = "ApparentlyTo",
  Approved = "Approved",
  ArcAuthenticationResults = "ArcAuthenticationResults",
  ArcMessageSignature = "ArcMessageSignature",
  ArcSeal = "ArcSeal",
  Archive = "Archive",
  ArchivedAt = "ArchivedAt",
  Article = "Article",
  AuthenticationResults = "AuthenticationResults",
  Autocrypt = "Autocrypt",
  AutocryptGossip = "AutocryptGossip",
  AutocryptSetupMessage = "AutocryptSetupMessage",
  Autoforwarded = "Autoforwarded",
  AutoSubmitted = "AutoSubmitted",
  Autosubmitted = "Autosubmitted",
  Base = "Base",
  Bcc = "Bcc",
  Body = "Body",
  Bytes = "Bytes",
  Cc = "Cc",
  Comments = "Comments",
  ContentAlternative = "ContentAlternative",
  ContentBase = "ContentBase",
  ContentClass = "ContentClass",
  ContentDescription = "ContentDescription",
  ContentDisposition = "ContentDisposition",
  ContentDuration = "ContentDuration",
  ContentFeatures = "ContentFeatures",
  ContentId = "ContentId",
  ContentIdentifier = "ContentIdentifier",
  ContentLanguage = "ContentLanguage",
  ContentLength = "ContentLength",
  ContentLocation = "ContentLocation",
  ContentMd5 = "ContentMd5",
  ContentReturn = "ContentReturn",
  ContentTransferEncoding = "ContentTransferEncoding",
  ContentTranslationType = "ContentTranslationType",
  ContentType = "ContentType",
  Control = "Control",
  Conversion = "Conversion",
  ConversionWithLoss = "ConversionWithLoss",
  Date = "Date",
  DateReceived = "DateReceived",
  DeferredDelivery = "DeferredDelivery",
  DeliveryDate = "DeliveryDate",
  DiscloseRecipients = "DiscloseRecipients",
  DispositionNotificationOptions = "DispositionNotificationOptions",
  DispositionNotificationTo = "DispositionNotificationTo",
  Distribution = "Distribution",
  DkimSignature = "DkimSignature",
  DomainKeySignature = "DomainKeySignature",
  Encoding = "Encoding",
  Encrypted = "Encrypted",
  Expires = "Expires",
  ExpiryDate = "ExpiryDate",
  FollowupTo = "FollowupTo",
  From = "From",
  GenerateDeliveryReport = "GenerateDeliveryReport",
  Importance = "Importance",
  InjectionDate = "InjectionDate",
  InjectionInfo = "InjectionInfo",
  InReplyTo = "InReplyTo",
  Keywords = "Keywords",
  Language = "Language",
  LatestDeliveryTime = "LatestDeliveryTime",
  Lines = "Lines",
  ListArchive = "ListArchive",
  ListHelp = "ListHelp",
  ListId = "ListId",
  ListOwner = "ListOwner",
  ListPost = "ListPost",
  ListSubscribe = "ListSubscribe",
  ListUnsubscribe = "ListUnsubscribe",
  ListUnsubscribePost = "ListUnsubscribePost",
  MessageId = "MessageId",
  MimeVersion = "MimeVersion",
  Newsgroups = "Newsgroups",
  NntpPostingHost = "NntpPostingHost",
  Organization = "Organization",
  OriginalFrom = "OriginalFrom",
  OriginalMessageId = "OriginalMessageId",
  OriginalRecipient = "OriginalRecipient",
  OriginalReturnAddress = "OriginalReturnAddress",
  OriginalSubject = "OriginalSubject",
  Path = "Path",
  Precedence = "Precedence",
  PreventNonDeliveryReport = "PreventNonDeliveryReport",
  Priority = "Priority",
  Received = "Received",
  ReceivedSPF = "ReceivedSPF",
  References = "References",
  RelayVersion = "RelayVersion",
  ReplyBy = "ReplyBy",
  ReplyTo = "ReplyTo",
  RequireRecipientValidSince = "RequireRecipientValidSince",
  ResentBcc = "ResentBcc",
  ResentCc = "ResentCc",
  ResentDate = "ResentDate",
  ResentFrom = "ResentFrom",
  ResentMessageId = "ResentMessageId",
  ResentReplyTo = "ResentReplyTo",
  ResentSender = "ResentSender",
  ResentTo = "ResentTo",
  ReturnPath = "ReturnPath",
  ReturnReceiptTo = "ReturnReceiptTo",
  SeeAlso = "SeeAlso",
  Sender = "Sender",
  Sensitivity = "Sensitivity",
  Solicitation = "Solicitation",
  Status = "Status",
  Subject = "Subject",
  Summary = "Summary",
  Supersedes = "Supersedes",
  TLSRequired = "TLSRequired",
  To = "To",
  UserAgent = "UserAgent",
  X400ContentIdentifier = "X400ContentIdentifier",
  X400ContentReturn = "X400ContentReturn",
  X400ContentType = "X400ContentType",
  X400MTSIdentifier = "X400MTSIdentifier",
  X400Originator = "X400Originator",
  X400Received = "X400Received",
  X400Recipients = "X400Recipients",
  X400Trace = "X400Trace",
  XMailer = "XMailer",
  XMSMailPriority = "XMSMailPriority",
  XPriority = "XPriority",
  XStatus = "XStatus",
  Unknown = "Unknown",
}

/** Maps known header identifiers to their canonical field names. */
export const headerIdNameTable = [
  [HeaderId.AcceptLanguage, "Accept-Language"],
  [HeaderId.AdHoc, "Ad-Hoc"],
  [HeaderId.AlternateRecipient, "Alternate-Recipient"],
  [HeaderId.ApparentlyTo, "Apparently-To"],
  [HeaderId.Approved, "Approved"],
  [HeaderId.ArcAuthenticationResults, "ARC-Authentication-Results"],
  [HeaderId.ArcMessageSignature, "ARC-Message-Signature"],
  [HeaderId.ArcSeal, "ARC-Seal"],
  [HeaderId.Archive, "Archive"],
  [HeaderId.ArchivedAt, "Archived-At"],
  [HeaderId.Article, "Article"],
  [HeaderId.AuthenticationResults, "Authentication-Results"],
  [HeaderId.Autocrypt, "Autocrypt"],
  [HeaderId.AutocryptGossip, "Autocrypt-Gossip"],
  [HeaderId.AutocryptSetupMessage, "Autocrypt-Setup-Message"],
  [HeaderId.Autoforwarded, "Autoforwarded"],
  [HeaderId.AutoSubmitted, "Auto-Submitted"],
  [HeaderId.Autosubmitted, "Autosubmitted"],
  [HeaderId.Base, "Base"],
  [HeaderId.Bcc, "Bcc"],
  [HeaderId.Body, "Body"],
  [HeaderId.Bytes, "Bytes"],
  [HeaderId.Cc, "Cc"],
  [HeaderId.Comments, "Comments"],
  [HeaderId.ContentAlternative, "Content-Alternative"],
  [HeaderId.ContentBase, "Content-Base"],
  [HeaderId.ContentClass, "Content-Class"],
  [HeaderId.ContentDescription, "Content-Description"],
  [HeaderId.ContentDisposition, "Content-Disposition"],
  [HeaderId.ContentDuration, "Content-Duration"],
  [HeaderId.ContentFeatures, "Content-Features"],
  [HeaderId.ContentId, "Content-Id"],
  [HeaderId.ContentIdentifier, "Content-Identifier"],
  [HeaderId.ContentLanguage, "Content-Language"],
  [HeaderId.ContentLength, "Content-Length"],
  [HeaderId.ContentLocation, "Content-Location"],
  [HeaderId.ContentMd5, "Content-Md5"],
  [HeaderId.ContentReturn, "Content-Return"],
  [HeaderId.ContentTransferEncoding, "Content-Transfer-Encoding"],
  [HeaderId.ContentTranslationType, "Content-Translation-Type"],
  [HeaderId.ContentType, "Content-Type"],
  [HeaderId.Control, "Control"],
  [HeaderId.Conversion, "Conversion"],
  [HeaderId.ConversionWithLoss, "Conversion-With-Loss"],
  [HeaderId.Date, "Date"],
  [HeaderId.DateReceived, "Date-Received"],
  [HeaderId.DeferredDelivery, "Deferred-Delivery"],
  [HeaderId.DeliveryDate, "Delivery-Date"],
  [HeaderId.DiscloseRecipients, "Disclose-Recipients"],
  [HeaderId.DispositionNotificationOptions, "Disposition-Notification-Options"],
  [HeaderId.DispositionNotificationTo, "Disposition-Notification-To"],
  [HeaderId.Distribution, "Distribution"],
  [HeaderId.DkimSignature, "DKIM-Signature"],
  [HeaderId.DomainKeySignature, "DomainKey-Signature"],
  [HeaderId.Encoding, "Encoding"],
  [HeaderId.Encrypted, "Encrypted"],
  [HeaderId.Expires, "Expires"],
  [HeaderId.ExpiryDate, "Expiry-Date"],
  [HeaderId.FollowupTo, "Followup-To"],
  [HeaderId.From, "From"],
  [HeaderId.GenerateDeliveryReport, "Generate-Delivery-Report"],
  [HeaderId.Importance, "Importance"],
  [HeaderId.InjectionDate, "Injection-Date"],
  [HeaderId.InjectionInfo, "Injection-Info"],
  [HeaderId.InReplyTo, "In-Reply-To"],
  [HeaderId.Keywords, "Keywords"],
  [HeaderId.Language, "Language"],
  [HeaderId.LatestDeliveryTime, "Latest-Delivery-Time"],
  [HeaderId.Lines, "Lines"],
  [HeaderId.ListArchive, "List-Archive"],
  [HeaderId.ListHelp, "List-Help"],
  [HeaderId.ListId, "List-Id"],
  [HeaderId.ListOwner, "List-Owner"],
  [HeaderId.ListPost, "List-Post"],
  [HeaderId.ListSubscribe, "List-Subscribe"],
  [HeaderId.ListUnsubscribe, "List-Unsubscribe"],
  [HeaderId.ListUnsubscribePost, "List-Unsubscribe-Post"],
  [HeaderId.MessageId, "Message-Id"],
  [HeaderId.MimeVersion, "MIME-Version"],
  [HeaderId.Newsgroups, "Newsgroups"],
  [HeaderId.NntpPostingHost, "Nntp-Posting-Host"],
  [HeaderId.Organization, "Organization"],
  [HeaderId.OriginalFrom, "Original-From"],
  [HeaderId.OriginalMessageId, "Original-Message-Id"],
  [HeaderId.OriginalRecipient, "Original-Recipient"],
  [HeaderId.OriginalReturnAddress, "Original-Return-Address"],
  [HeaderId.OriginalSubject, "Original-Subject"],
  [HeaderId.Path, "Path"],
  [HeaderId.Precedence, "Precedence"],
  [HeaderId.PreventNonDeliveryReport, "Prevent-NonDelivery-Report"],
  [HeaderId.Priority, "Priority"],
  [HeaderId.Received, "Received"],
  [HeaderId.ReceivedSPF, "Received-SPF"],
  [HeaderId.References, "References"],
  [HeaderId.RelayVersion, "Relay-Version"],
  [HeaderId.ReplyBy, "Reply-By"],
  [HeaderId.ReplyTo, "Reply-To"],
  [HeaderId.RequireRecipientValidSince, "Require-Recipient-Valid-Since"],
  [HeaderId.ResentBcc, "Resent-Bcc"],
  [HeaderId.ResentCc, "Resent-Cc"],
  [HeaderId.ResentDate, "Resent-Date"],
  [HeaderId.ResentFrom, "Resent-From"],
  [HeaderId.ResentMessageId, "Resent-Message-Id"],
  [HeaderId.ResentReplyTo, "Resent-Reply-To"],
  [HeaderId.ResentSender, "Resent-Sender"],
  [HeaderId.ResentTo, "Resent-To"],
  [HeaderId.ReturnPath, "Return-Path"],
  [HeaderId.ReturnReceiptTo, "Return-Receipt-To"],
  [HeaderId.SeeAlso, "See-Also"],
  [HeaderId.Sender, "Sender"],
  [HeaderId.Sensitivity, "Sensitivity"],
  [HeaderId.Solicitation, "Solicitation"],
  [HeaderId.Status, "Status"],
  [HeaderId.Subject, "Subject"],
  [HeaderId.Summary, "Summary"],
  [HeaderId.Supersedes, "Supersedes"],
  [HeaderId.TLSRequired, "TLS-Required"],
  [HeaderId.To, "To"],
  [HeaderId.UserAgent, "User-Agent"],
  [HeaderId.X400ContentIdentifier, "X400-Content-Identifier"],
  [HeaderId.X400ContentReturn, "X400-Content-Return"],
  [HeaderId.X400ContentType, "X400-Content-Type"],
  [HeaderId.X400MTSIdentifier, "X400-MTS-Identifier"],
  [HeaderId.X400Originator, "X400-Originator"],
  [HeaderId.X400Received, "X400-Received"],
  [HeaderId.X400Recipients, "X400-Recipients"],
  [HeaderId.X400Trace, "X400-Trace"],
  [HeaderId.XMailer, "X-Mailer"],
  [HeaderId.XMSMailPriority, "X-MSMail-Priority"],
  [HeaderId.XPriority, "X-Priority"],
  [HeaderId.XStatus, "X-Status"],
] as const;

/** A known header identifier, excluding {@link HeaderId.Unknown}. */
export type KnownHeaderId = Exclude<HeaderId, HeaderId.Unknown>;

const idToName = new Map<HeaderId, string>(headerIdNameTable);
const nameToId = new Map<string, HeaderId>(headerIdNameTable.map(([id, name]) => [name.toLowerCase(), id]));

/**
 * Gets the canonical header field name for a header identifier.
 *
 * @param value The header identifier.
 * @returns The canonical field name, or `Unknown` if it is not recognized.
 */
export function toHeaderName(value: HeaderId | string | number): string {
  if (typeof value === 'number') return 'Unknown';
  return idToName.get(value as HeaderId) ?? 'Unknown';
}

/**
 * Gets the header identifier for a field name.
 *
 * @param name The header field name.
 * @returns The matching header identifier, or {@link HeaderId.Unknown}.
 */
export function toHeaderId(name: string | null | undefined): HeaderId {
  if (name == null) return HeaderId.Unknown;
  return nameToId.get(name.toLowerCase()) ?? HeaderId.Unknown;
}
